language: android

before_script:
  - mkdir deploy

cache:
  - $HOME/.cache
  - $HOME/.gradle

matrix:
    fast_finish: true
    include:
      - os: linux
        env: TARGET=Android NDK_VERSION=r13b TERM=dumb
        android:
          components:
            - platform-tools
            - tools
            - build-tools-25.0.2
            - android-24
        jdk: oraclejdk8
        before_install:
          - 'if [[ ! -d "$HOME/.cache/android-ndk-$NDK_VERSION" ]]; then
                mkdir -p $HOME/.cache;
                pushd $HOME/.cache;
                wget http://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip;
                unzip android-ndk-$NDK_VERSION-linux-x86_64.zip > /dev/null;
                rm android-ndk-$NDK_VERSION-linux-x86_64.zip;
                popd;
            fi'
          - export ANDROID_NDK_HOME="$HOME/.cache/android-ndk-$NDK_VERSION"
          - export PATH=${PATH}:${ANDROID_NDK_HOME}
          - cd SDL2
          - wget https://www.libsdl.org/release/SDL2-2.0.5.zip
          - unzip SDL2-2.0.5.zip
          - mv SDL2-2.0.5/* .
          - cd ..
        script:
          - cd android
          - ./gradlew assembleDebug
          - mv app/build/outputs/apk/app-debug.apk ../deploy/sdlpal-debug.apk
          - cd ..