os:
    - linux
    - osx

dist: 
    - trusty
    - precise

language: android

env:
    matrix:
    - TARGET=linux
    - TARGET=android
    - TARGET=ios
    - TARGET=macos

matrix:
    exclude:
      - os: linux
        env: TARGET=ios
      - os: linux
        env: TARGET=macos
      - os: osx
        env: TARGET=linux
      - os: osx
        env: TARGET=android

before_install:
  - mkdir deploy
  - 'if [[ "$TARGET" == "macos" ]]; then 
        wget https://www.libsdl.org/release/SDL2-2.0.5.dmg;
        hdiutil attach SDL2-2.0.5.dmg;
        sudo cp -a /Volumes/SDL2/SDL2.framework /Library/Frameworks/;
    fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        sudo apt-get update -qq;
        sudo apt-get install -qq libsdl2-dev libfltk1.3-dev;
    fi'
  - 'if [[ "$TARGET" == "android" || "$TARGET" == "ios" ]]; then 
        cd SDL2;
        wget https://www.libsdl.org/release/SDL2-2.0.5.zip;
        unzip SDL2-2.0.5.zip;
        mv SDL2-2.0.5/* ..;
    fi'

script:
  - 'if [[ "$TARGET" == "linux" ]]; then 
        cd unix;
        make;
        cp sdlpal ../deploy;
        make clean;
        make check;
    fi'
  - 'if [[ "$TARGET" == "macos" ]]; then 
        cd macos;
        xcodebuild;
        hdiutil create -srcfolder Pal.app -volname "SDLPal" ../deploy/sdlpal-macos.dmg;
        xcodebuild test -scheme PalTests;
    fi'
  - 'if [[ "$TARGET" == "android" ]]; then 
        cd android/jni;
        ndk-build;
        cd ..;
        ant debug;
        mv build;
    fi'
  - 'if [[ "$TARGET" == "ios" ]]; then 
        cd ios/SDLPal;
        xcodebuild ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO;
        mkdir -p Payload;
        mv build/Release-iphoneos/SDLPal.app Payload;
        zip ../deploy/sdlpal-impactor.ipa -r Payload;
    fi'

deploy:
    on:
        tags: true